services:
  base: &base
    image: navi:dev
    env_file: .env
    volumes:
      - ./source:/home/node/app
      - ./docker_volumes/config:/home/node/app/config
      - ./docker_volumes/node_modules:/home/node/app/node_modules

  base_build:
    <<: *base
    container_name: navi_build
    build:
      context: .
      dockerfile: dockerfiles/dev_navy/Dockerfile
    command: echo done

  navi_app:
    <<: *base
    container_name: navi_app
    depends_on: [base_build, navi_proxy]
    command: /bin/bash
    links:
      - navi_proxy:remote_host

  navi_tests:
    <<: *base
    container_name: navi_tests
    depends_on: [base_build]
    command: /bin/bash

  navi_proxy:
    image: darthjee/tent:0.5.0
    depends_on: [navi_dev_app]
    links:
      - navi_dev_app:backend
    volumes:
      - ./docker_volumes/proxy_configuration:/var/www/html/configuration/
      - ./docker_volumes/proxy_cache:/var/www/html/cache/
    ports:
      - 0.0.0.0:3010:80

  navi_dev_app:
    image: navi_app:dev
    build:
      context: .
      dockerfile: dockerfiles/dev_app/Dockerfile
    command: node server.js
    volumes:
      - ./dev/:/home/node/app/
      - ./docker_volumes/node_modules_dev:/home/node/app/node_modules
    ports:
      - 0.0.0.0:3020:80
