web:
  port: 3000
workers:
  quantity: 5
clients:
  default:
    base_url: http://remote_host:80
    timeout: 5000
resources:
  categories:
    - url: /categories.json
      status: 200
      actions:
        - resource: category
          parameters:
            id: parsedBody.id
        - resource: category_items
          parameters:
            id: parsedBody.id
  category:
    - url: /categories/{:id}.json
      status: 200
  category_items:
    - url: /categories/{:id}/items.json
      status: 200
