version: 2.1

workflows:
  test-and-release:
    jobs:
      - jasmine:
          filters:
            tags:
              only: /.*/
      - checks:
          filters:
            tags:
              only: /.*/

jobs:
  jasmine:
    docker:
      - image: darthjee/circleci_node:0.2.1
    steps:
      - checkout
      - run:
          name: Set folder
          command: mv source/* ./; rm -rf source/
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Unit tests (Jasmine)
          command: npm run coverage
      - run:
          name: Upload coverage to Codacy
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info
  checks:
    docker:
      - image: darthjee/circleci_node:0.2.1
    steps:
      - checkout
      - run:
          name: Set folder
          command: mv source/* ./; rm -rf source/
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Duplication report (JSCPD)
          command: npm run report
